# Generated by Django 5.2.4 on 2025-07-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='comentario',
            field=models.TextField(blank=True, help_text='Personalización del plato (sin sal, extra queso, etc.)'),
        ),
    ]
