# Generated by Django 5.2.4 on 2025-09-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='para_llevar',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='para_llevar',
            field=models.BooleanField(default=False),
        ),
    ]
